############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Students"
url = "/students"
weight = 2

[[main]]
name = "Partners"
url = "/partners"
weight = 3

[[main]]
weight = 4
name = "About"
url = "/about"

[[main]]
name = "Contact"
url = "/contact"


# footer menu
[[footer]]
name = "Terms & Conditions"
url = "/terms"
weight = 1
[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 2

[[footer]]
name = "Cookie Policy"
url = "/cookie-policy"
weight = 3

